### ISSUE TITLE
Getting error while posting status

### ISSUE THREAD

**Issue by Shurlow** [wkentdag/sup#19]
/Users/shurlow/code/sup/routes/status.js:64
    viewer_ids.push(statusObj.owner_id);
              ^
TypeError: Cannot read property 'push' of undefined
    at /Users/shurlow/code/sup/routes/status.js:64:15
    at /Users/shurlow/code/sup/node_modules/pg/lib/pool.js:77:9
    at /Users/shurlow/code/sup/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:281:11
    at /Users/shurlow/code/sup/node_modules/pg/lib/pool.js:51:18
    at null.<anonymous> (/Users/shurlow/code/sup/node_modules/pg/lib/client.js:144:7)
    at g (events.js:199:16)
    at emit (events.js:129:20)
    at Socket.<anonymous> (/Users/shurlow/code/sup/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
4 May 00:48:06 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by wkentdag** [comment]
are you running the server in production or dev mode?

**Comment by Shurlow** [comment]
hmmm can't remember, but I think I probably wasn't...
